name = "skeletona"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./landing/dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "WAITLIST_KV"
id = "383234a96eeb4689a59e27d0a9f51bbb"
